version: "3.8"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stkadmin
      POSTGRES_PASSWORD: YWdlbnRkZW1vYWRtaW4K
      POSTGRES_DB: agent-demo
    volumes:
      - ./_scripts/postgres:/docker-entrypoint-initdb.d
    networks:
      - main

  mongodb-primary:
    container_name: mongodb-primary
    image: 'docker.io/bitnami/mongodb:latest'
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-primary
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_USERNAME=stkadmin 
      - MONGODB_ROOT_PASSWORD=YWdlbnRkZW1vYWRtaW4K 
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    ports:
      - "27017:27017"
    networks:
      - main

  mongodb-secondary:
    container_name: mongodb-secondary
    image: 'docker.io/bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    ports:
      - "27018:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-secondary
      - MONGODB_REPLICA_SET_MODE=secondary
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=YWdlbnRkZW1vYWRtaW4K
      - MONGODB_INITIAL_PRIMARY_ROOT_USERNAME=stkadmin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - main

  mongodb-arbiter:
    container_name: mongodb-arbiter
    image: 'docker.io/bitnami/mongodb:latest'
    depends_on:
      - mongodb-primary
    ports:
      - "27019:27017"
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=mongodb-arbiter
      - MONGODB_REPLICA_SET_MODE=arbiter
      - MONGODB_INITIAL_PRIMARY_HOST=mongodb-primary
      - MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD=YWdlbnRkZW1vYWRtaW4K
      - MONGODB_INITIAL_PRIMARY_ROOT_USERNAME=stkadmin
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
    networks:
      - main

networks:
  main:
